[package]
name = "btls"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14"
pest = "2.7"
pest_derive = "2.7"
tower-lsp = "0.20"
tokio = { version = "1.47", features = ["io-std", "io-util", "macros", "process", "rt-multi-thread", "sync"] }
serde = "1.0"
serde_json = "1.0"
