WHITESPACE = _{ (" " | "\t" | "\r" | "\n")+ }
SPACE      = _{ " " | "\t" }
COMMENT    = _{ "//" ~ (!NEWLINE ~ ANY)* ~ NEWLINE? }
NEWLINE    = _{ "\r\n" | "\n" }

identifier = @{ (ASCII_ALPHANUMERIC | "_")+ }
string     = @{ "\"" ~ (!"\"" ~ ANY)* ~ "\"" }
number     = @{ ASCII_DIGIT+ }

primary   =  {
    string
  | number
  | call
  | identifier
  | variable
}
scratch_var = { "$" ~ identifier }
map_var     = { "@" ~ (identifier ~ map_keys? | map_keys)? }
variable    = { scratch_var | map_var }
map_keys  =  { "[" ~ expr_list ~ "]" }
expr      =  { prefix* ~ primary ~ postfix* ~ (infix ~ prefix* ~ primary ~ postfix*)* }
expr_list =  { expr ~ ("," ~ expr)* }
infix     = _{ add | sub | mul | div | le | lt | ge | gt | eq | ne | and | or }
prefix    = _{ not | inc_prefix | dec_prefix | neg | pos }
postfix   = _{ inc_postfix | dec_postfix }
inc_prefix    =  { "++" }
inc_postfix   =  { "++" }
dec_prefix    =  { "--" }
dec_postfix   =  { "--" }
add       =  { "+" }
sub       =  { "-" }
mul       =  { "*" }
div       =  { "/" }
le        =  { "<=" }
lt        =  { "<" }
ge        =  { ">=" }
gt        =  { ">" }
eq        =  { "==" }
ne        =  { "!=" }
and       =  { "&&" }
or        =  { "||" }
not       =  { "!" }
neg       =  { "-" }
pos       =  { "+" }

assign_op  =  { "=" | "+=" | "-=" }
assignment =  { variable ~ assign_op ~ expr }
call       =  { identifier ~ "(" ~ expr_list? ~ ")" }
if         =  { "if" ~ "(" ~ expr ~ ")" ~ block ~ else? }
else       =  { "else" ~ (if | block) }
while      =  { "while" ~ "(" ~ expr ~ ")" ~ block }
for        =  { "for" ~ "(" ~ expr ~ ":" ~ expr ~ ")" ~ block }
unroll     =  { "unroll" ~ "(" ~ number ~ ")" ~ block }
base_stmt  = _{ assignment | expr }
statement  =  { base_stmt ~ ";" | if | while | for | unroll }
block      =  { "{" ~ (COMMENT | statement | error)* ~ "}" }

attach_point      = @{ (identifier | ":" | "*")+ }
attach_point_list = { attach_point ~ ("," ~ attach_point)* }
probe_condition   = { "/" ~ expr ~ "/" }
probe             = { attach_point_list ~ probe_condition? ~ block }

cdef         = { include | define }
include      = ${ "#include" ~ SPACE+ ~ include_path }
include_path = @{ "<" ~ (!(">" | NEWLINE) ~ ANY)* ~ ">" }
define       = ${ "#define" ~ SPACE+ ~ identifier ~ (SPACE+ ~ define_body)? }
define_body  = @{ (!NEWLINE ~ ANY)+ }

cfg_value  = { identifier | number | string }
cfg_assign = { identifier ~ "=" ~ cfg_value? ~ ";"? }
cfg_block  = { "config" ~ "=" ~ "{" ~ (COMMENT | cfg_assign | error)* ~ "}" }

preamble          = { cfg_block | probe | cdef }

error        =  { rest_of_line }
rest_of_line = @{ (!(NEWLINE | "}") ~ ANY)+ ~ NEWLINE? }

unmatched_brace = { "}" }
program         = { SOI ~ (COMMENT | preamble | error | unmatched_brace)* ~ EOI }
