name: Formatter and Linter

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'README.md'

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - run: cargo install pest_fmt
    - name: rustfmt
      run: cargo fmt --check
    - name: pestfmt
      run: |
        pestfmt src/parser/bpftrace.pest
        git diff --exit-code src/parser/bpftrace.pest
